//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeInRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTimeOut
    {
        public int TimeInId { get; set; }
        public int EmployeeId { get; set; }
        public int ActivityCd { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeOutDttm { get; set; }
        public System.DateTime CreateDttm { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateDttm { get; set; }
        public string UpdateUserId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}
